# Generated by Django 4.1.7 on 2023-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
